cmd1 = [
    "jarvis",
    "hello",
    "hi",
    "hy",
    "hello jarvis",
    "hello mister jarvis",
    "hello mr jarvis",
    "jarvis wake up",
    "hey jarvis",
    "wake up jarvis",
    "jarvis, are you there?",
    "hello jarvis, it's time",
    "jarvis, wake up now",
    "rise and shine, jarvis",
    "jarvis, time to activate",
    "good morning, jarvis",
    "jarvis ready for action",
    "hello there, jarvis",
    "jarvis, it's showtime",
    "wakey-wakey, jarvis",
    "hey there, jarvis",
    "jarvis, the world awaits",
    "hello, jarvis, my friend",
    "jarvis, time to get up",
    "rise and shine, mr. jarvis",
    "jarvis, the day has come",
    "hello, my dear jarvis",
    "jarvis, are you online?",
    "good to see you, jarvis",
    "jarvis, ready to assist?",
    "hello jarvis, my assistant",
    "jarvis, it's go time",
    "wake up, jarvis, wake up",
    "hey jarvis, how are you?",
    "jarvis, showtime begins",
    "hello jarvis, my companion",
    "jarvis, ready for duty",
    "rise and shine, my jarvis",
    "jarvis, it's time to work",
    "good morning, mr. jarvis",
    "jarvis, activate now",
    "hello jarvis, my partner",
    "jarvis, time for greatness",
    "jarvis, let's get started",
    "hey there, mr. jarvis",
    "jarvis, the world awaits you",
    "jarvis, ready for action",
    "rise and shine, jarvis dear",
    "jarvis, time to shine",
    "hello jarvis, it's your time",
    "jarvis, the day is here",
    "jarvis, are you listening?",
    "good morning, jarvis dear",
    "jarvis, ready when you are",
    "hello jarvis, my friend",
    "jarvis, it's go time now",
    "wake up, jarvis, wake up now",
    "hey jarvis, time to wake up",
    "jarvis, the world needs you",
    "hello jarvis, my loyal assistant",
    "jarvis, time to take charge"]

res1 = [
    "hello sir! jarvis is here",
    "greetings sir! jarvis reporting in",
    "hello there! jarvis is at your service",
    "good day sir! jarvis is present",
    "salutations sir! jarvis reporting for duty",
    "hi there! jarvis is here to assist",
    "hello sir! jarvis is ready and waiting",
    "greetings sir! jarvis is on standby",
    "hello there! jarvis is at your command",
    "good day sir! jarvis is online",
    "salutations sir! jarvis is here to help",
    "hi there! jarvis is ready for interaction",
    "hello sir! jarvis is in action",
    "greetings sir! jarvis is at your disposal",
    "hello there! jarvis is at your beck and call",
    "good day sir! jarvis is ready to serve",
    "salutations sir! jarvis is at your beckoning",
    "hi there! jarvis is here for you",
    "hello sir! jarvis is here and listening",
    "greetings sir! jarvis is ready to respond",
    "hello there! jarvis is awaiting your command",
    "good day sir! jarvis is here and attentive",
    "salutations sir! jarvis is prepared to assist",
    "hi there! jarvis is at your service",
    "hello sir! jarvis is here and operational",
    "greetings sir! jarvis is at your beck and call",
    "hello there! jarvis is standing by",
    "good day sir! jarvis is here to support",
    "salutations sir! jarvis is ready for your orders",
    "hi there! jarvis is at your service",
    "hello sir! jarvis is here and ready",
    "greetings sir! jarvis is at your disposal",
    "hello there! jarvis is here and responsive",
    "good day sir! jarvis is at your command",
    "salutations sir! jarvis is standing by for you",
    "hi there! jarvis is ready and available",
    "hello sir! jarvis is here and at your service",
    "greetings sir! jarvis is on standby for you",
    "hello there! jarvis is here and awaiting instructions",
    "good day sir! jarvis is ready for your guidance",
    "salutations sir! jarvis is here and prepared",
    "hi there! jarvis is at your disposal",
    "hello sir! jarvis is here and attentive",
    "greetings sir! jarvis is at your command",
    "hello there! jarvis is ready to assist",
    "good day sir! jarvis is here and responsive",
    "salutations sir! jarvis is at your service",
    "hi there! jarvis is standing by for your orders"

]

stopcmd = [
    "stop listening",
    "go to sleep",
    "jarvis sleep now"

]

stopdlg = [
    "okay sir, farewell",
    "okay sir, goodbye",
    "okay sir, see you later",
    "okay sir, until next time",
    "alright sir, adieu",
    "alright sir, take care",
    "alright sir, goodbye for now",
    "sure sir, see you around",
    "sure sir, until we meet again",
    "understood sir, farewell",
    "understood sir, bye",
    "understood sir, take care",
    "affirmative sir, goodbye",
    "affirmative sir, until next time",
    "affirmative sir, see you later",
    "roger that sir, farewell",
    "roger that sir, goodbye",
    "roger that sir, bye bye",
    "acknowledged sir, take care",
    "acknowledged sir, see you around",
    "acknowledged sir, until next time",
    "got it sir, farewell",
    "got it sir, goodbye",
    "got it sir, bye bye",
    "okay sir, adieu",
    "okay sir, until we meet again",
    "okay sir, farewell for now",
    "alright sir, see you soon",
    "alright sir, take it easy",
    "alright sir, until later",
    "sure sir, farewell",
    "sure sir, goodbye for now",
    "sure sir, until we meet again",
    "understood sir, see you soon",
    "understood sir, take it easy",
    "understood sir, until later",
    "affirmative sir, farewell for now",
    "affirmative sir, see you soon",
    "affirmative sir, take it easy",
    "roger that sir, until later",
    "roger that sir, farewell for now",
    "roger that sir, see you soon",
    "acknowledged sir, until later",
    "acknowledged sir, farewell for now",
    "acknowledged sir, see you soon",
    "got it sir, until later",
    "got it sir, farewell for now",
    "got it sir, see you soon"
]

open_dld = [
    f"opening...",
    f"just a second opening",
    f"ok i am gonna open ",
    f"as your wish opening ",
    f"yes sir opening ",
    f"trying to open ",
    f"starting ",
    f"here we go opening",

]

playdlg = [
    "playing..",
    "yes sir",
    "doing..",
    "playing now"
]

pausedlg = [
    "pausing",
    "stoping",
    "doing",
    "as your wish"
]

closedlg = [
    "closing",
    "close",
    "just a second sir",
    "got it sir"
]